ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
  hosts:
    - host: nats.$DOMAIN
      paths:
        - path: /
          pathType: Prefix